- name: test stat module
  hosts: all
  tasks:
    - name: Ensure 7-Zip is installed through Chocolatey
      win_chocolatey:
        name: 7zip
        state: present

    - name: Ensure 7-Zip is not installed through Chocolatey
      win_chocolatey:
        name: 7zip
        state: absent

    # Install/uninstall with win_package
    - name: Download the 7-Zip package
      win_get_url:
        url: https://www.7-zip.org/a/7z2301-x64.msi
        dest: C:\temp\7z.msi

    - name: Ensure 7-Zip is installed through win_package
      win_package:
        path: C:\temp\7z.msi
        state: present

    - name: Ensure 7-Zip is not installed through win_package
      win_package:
        path: C:\temp\7z.msi
        state: absent

    # Install/uninstall with win_command
    - name: Download the 7-Zip package
      win_get_url:
        url: https://www.7-zip.org/a/7z2301-x64.msi
        dest: C:\temp\7z.msi

    - name: Check if 7-Zip is already installed
      win_reg_stat:
        path: HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall
        name: 7-zip
      register: installed7zip

    - name: Ensure 7-Zip is installed through win_command
      win_command: C:\Windows\System32\msiexec.exe /i C:\temp\7z.msi /qn /norestart
      when: installed7zip.exists == false

    - name: Ensure 7-Zip is uninstalled through win_command
      win_command: C:\Windows\System32\msiexec.exe /x 7-zip /qn /norestart
      when: installed7zip.exists == true
